### ISSUE TITLE
Differing height of header outlines

### ISSUE THREAD

**Issue by shortdiv** [NUKnightLab/storyline#28]
Not sure if we should standardize the height of the headers, the standard being 2 lined headers so it looks neater across the board. Attached gif for reference.

http://g.recordit.co/6a32ZEaUZ6.gif

**Comment by JoeGermuska** [comment]
@zachwise says yes

**Comment by JoeGermuska** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [min-height for header section of cards](https://trello.com/c/sKXZx2x2/93-min-height-for-header-section-of-cards)

**Comment by JoeGermuska** [comment]
@shortdiv should this be closed?
