### ISSUE TITLE
Add support for Hammer.js swipes in addition to pans for better mobile use

### ISSUE THREAD

**Issue by duner** [NUKnightLab/storyline#30]
On mobile, I often find that I want to swipe and not pan when going through the cards. https://hammerjs.github.io/recognizer-swipe/

**Comment by JoeGermuska** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for Hammer.js swipes in addition to pans for better mobile use #30](https://trello.com/c/yxdYkCG5/92-add-support-for-hammer-js-swipes-in-addition-to-pans-for-better-mobile-use-30)
