### ISSUE TITLE
Discrepancy between circle tests and local tests

### ISSUE THREAD

**Issue by shortdiv** [NUKnightLab/storyline#48]
Building tests locally shows passing tests
<img width="861" alt="screen shot 2017-06-09 at 12 15 01 pm" src="https://user-images.githubusercontent.com/3229484/26986460-4adb2d32-4d0d-11e7-8fea-5bb5e991f01a.png">

CircleCI shows otherwise:
<img width="1919" alt="screen shot 2017-06-09 at 12 15 55 pm" src="https://user-images.githubusercontent.com/3229484/26986506-6cb69ffe-4d0d-11e7-89cc-d3acbf9887dc.png">

This is from the latest build as of 12:04 on 06/06/17 git SHA -> 22f0dec5561fc449efe2bfaed643263e04bd566d

**Comment by JoeGermuska** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix unit tests or remove Circle-CI](https://trello.com/c/NLHnpmd3/117-fix-unit-tests-or-remove-circle-ci)

**Comment by JoeGermuska** [comment]
what's the relationship between this and #7 ? Can one be closed?
