### ISSUE TITLE
Silent Error when creating a storyline

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/storyline#50]
Making a copy of this spreadsheet: https://docs.google.com/spreadsheets/u/1/d/1akG6LMDBK385b_GXE85T4JyTBtyoPZVaW5NYT0iCoWE/copy

Publishing it to the web and then selecting inappropriate columns creates a silent error with no user feedback.

```
gui.js:13 Uncaught (in promise) Error
    at i.lib.get.then.n.errorMessage (gui.js:13)
    at <anonymous>
i.lib.get.then.n.errorMessage	@	gui.js:13
```
![screenshot jun 14 13 43 03](https://user-images.githubusercontent.com/741789/27149003-c4e36a24-5107-11e7-8cdf-3760ad50db82.png)

**Comment by shortdiv** [comment]
I'm using the copy of the spreadsheet and I seem to be hitting a CORS error. What is the url you're using exactly?

**Comment by shortdiv** [comment]
I reproduced the error according to the above steps. As expected, I seem to be getting an error message in the storyline element indicating to the user what the error is related to. 

<img width="1919" alt="error-message" src="https://user-images.githubusercontent.com/3229484/27150665-b3b2c05a-510d-11e7-934c-c4eb3c97dcb9.png">

**Comment by JoeGermuska** [comment]
I've asked @zachwise to provide a more complete specification of how the form should behave: error messaging should be adjacent to relevant fields, he has ideas (sketched on the conf room white board) about clustering the form elements for better understanding...  

Seeing what you say about the CORS error, we should make sure to apply in-place error messaging for the spreadsheet input field as well as the select elements and give a clear message about that too

**Comment by JoeGermuska** [comment]
Can't reproduce. I think this is from earlier versions of the code.
